info: {}
name: pad_array_Ppad_C1_R3_CP_707f34aa
settings:
  auto_rename_ports: false
  centered_ports: false
  column_pitch: 150
  columns: 1
  layer: MTOP
  pad: pad
  port_orientation: 180
  row_pitch: 150
  rows: 3
