info:
  length: 818.7
name: spiral_racetrack_MR5_SL_7ab1ec43
settings:
  allow_min_radius_violation: false
  bend: bend_euler
  bend_s: bend_s
  cross_section: strip
  extra_90_deg_bend: false
  min_radius: 5
  spacings:
  - 2
  - 2
  - 3
  - 3
  - 2
  - 2
  straight: straight
  straight_length: 20
  with_inner_ports: false
